<a href="index.php">HOME</a><BR>
<a href="pag1.php">ÁRIES</a><BR>
<a href="pag2.php">TOURO</a><BR>
<a href="pag3.php">GÊMEOS</a><BR>
<a href="pag4.php">CÂNCER</a><BR>
<a href="pag5.php">LEÃO</a><BR>
<a href="pag6.php">VIRGEM</a><BR>
<a href="pag7.php">LIBRA</a><BR>
<a href="pag8.php">ESCORPIÃO</a><BR>
<a href="pag9.php">SAGITÁRIO</a><BR>
<a href="pag10.php">CAPRICÓRNIO</a><BR>
<a href="pag11.php">AQUÁRIO</a><BR>
<a href="pag12.php">PEIXES</a><BR>
<a href="contato.php" target="_blank">CONTATO</a><BR>